-- Store avatar images inline so the shop does not depend on /avatars/*.svg
-- static files (those 404 on the deployed site until public assets are shipped).

UPDATE public.avatars
SET image_url = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij4KICA8Y2lyY2xlIGN4PSI2NCIgY3k9IjY0IiByPSI2MCIgZmlsbD0iIzMzNDE1NSIgc3Ryb2tlPSIjOTRhM2I4IiBzdHJva2Utd2lkdGg9IjYiLz4KICA8cGF0aCBmaWxsPSIjZTJlOGYwIiBkPSJNNjQgMjhjLTggMC0xNCA2LTE0IDE0IDAgNSAzIDkgNyAxMS04IDMtMTQgMTEtMTQgMjF2NGg0MnYtNGMwLTEwLTYtMTgtMTQtMjEgNC0yIDctNiA3LTExIDAtOC02LTE0LTE0LTE0em0tMjAgNTZjMCA4IDggMTQgMjAgMTYgMTItMiAyMC04IDIwLTE2SDQ0eiIvPgo8L3N2Zz4K'
WHERE name = 'Pawn'
   OR image_url IN ('/avatars/pawn.svg', 'pawn.svg');

UPDATE public.avatars
SET image_url = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij4KICA8Y2lyY2xlIGN4PSI2NCIgY3k9IjY0IiByPSI2MCIgZmlsbD0iIzFlM2E1ZiIgc3Ryb2tlPSIjMzhiZGY4IiBzdHJva2Utd2lkdGg9IjYiLz4KICA8cGF0aCBmaWxsPSIjZTBmMmZlIiBkPSJNNjQgMjJjLTMgMC02IDMtNiA3IDAgMiAxIDQgMyA1LTkgOC0xNiAyMC0xNiAzMiAwIDggNCAxNCAxMCAxOEg0NXY4aDM4di04SDczYzYtNCAxMC0xMCAxMC0xOCAwLTEyLTctMjQtMTYtMzIgMi0xIDMtMyAzLTUgMC00LTMtNy02LTd6bS0xOCA3MGMwIDYgOCAxMCAxOCAxMiAxMC0yIDE4LTYgMTgtMTJINDZ6Ii8+CiAgPGNpcmNsZSBjeD0iNjQiIGN5PSI0OCIgcj0iNCIgZmlsbD0iIzFlM2E1ZiIvPgo8L3N2Zz4K'
WHERE name = 'Bishop'
   OR image_url IN ('/avatars/bishop.svg', 'bishop.svg');

UPDATE public.avatars
SET image_url = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij4KICA8Y2lyY2xlIGN4PSI2NCIgY3k9IjY0IiByPSI2MCIgZmlsbD0iIzNmMmExNCIgc3Ryb2tlPSIjZDk3NzA2IiBzdHJva2Utd2lkdGg9IjYiLz4KICA8cGF0aCBmaWxsPSIjZmRlNjhhIiBkPSJNODYgOTBINDJjMC02IDQtMTAgOC0xNC0xMC00LTE2LTE0LTE0LTI2IDItMTAgMTAtMTYgMjAtMjAgMi02IDgtMTIgMTYtMTQgMiA4LTIgMTYtOCAyMCAxMCAyIDIwIDEwIDIyIDIyIDIgMTAtMiAxOC04IDI0IDYgMiAxMCA2IDggOHoiLz4KICA8Y2lyY2xlIGN4PSI1OCIgY3k9IjQ2IiByPSIzIiBmaWxsPSIjM2YyYTE0Ii8+Cjwvc3ZnPgo='
WHERE name = 'Knight'
   OR image_url IN ('/avatars/knight.svg', 'knight.svg');

UPDATE public.avatars
SET image_url = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij4KICA8Y2lyY2xlIGN4PSI2NCIgY3k9IjY0IiByPSI2MCIgZmlsbD0iIzFlMjkzYiIgc3Ryb2tlPSIjNjQ3NDhiIiBzdHJva2Utd2lkdGg9IjYiLz4KICA8cGF0aCBmaWxsPSIjY2JkNWUxIiBkPSJNMzggMjhoMTJ2MTBoOFYyOGgxMnYxMGg4VjI4aDEydjIySDM4VjI4em00IDI2aDQ0djI4SDQyVjU0em0tNiAzMmg1NnYxMEgzNlY4NnoiLz4KPC9zdmc+Cg=='
WHERE name = 'Rook'
   OR image_url IN ('/avatars/rook.svg', 'rook.svg');

UPDATE public.avatars
SET image_url = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij4KICA8Y2lyY2xlIGN4PSI2NCIgY3k9IjY0IiByPSI2MCIgZmlsbD0iIzRjMWQ5NSIgc3Ryb2tlPSIjZjU5ZTBiIiBzdHJva2Utd2lkdGg9IjYiLz4KICA8cGF0aCBmaWxsPSIjZmRlNjhhIiBkPSJNNjQgMjRsOCAxOCAxOC0xMC02IDIyIDIwIDItMTYgMTZINDBMMjQgNTZsMjAtMi02LTIyIDE4IDEwIDgtMTh6bS0yMiA2NGg0NGMwIDgtOCAxNC0yMiAxNi0xNC0yLTIyLTgtMjItMTZ6Ii8+Cjwvc3ZnPgo='
WHERE name = 'Queen'
   OR image_url IN ('/avatars/queen.svg', 'queen.svg');

UPDATE public.avatars
SET image_url = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjggMTI4Ij4KICA8Y2lyY2xlIGN4PSI2NCIgY3k9IjY0IiByPSI2MCIgZmlsbD0iIzFlM2E4YSIgc3Ryb2tlPSIjZmJiZjI0IiBzdHJva2Utd2lkdGg9IjYiLz4KICA8cGF0aCBmaWxsPSIjZmJiZjI0IiBkPSJNNTggMjJoMTJ2MTBoMTB2MTBINzB2OEg1OHYtOEg0OFYzMmgxMFYyMnoiLz4KICA8cGF0aCBmaWxsPSIjZmRlNjhhIiBkPSJNNDAgNTRoNDhsLTYgMjhINDZMNDAgNTR6bTYgMzJoMzZjMCA4LTggMTQtMTggMTYtMTAtMi0xOC04LTE4LTE2eiIvPgo8L3N2Zz4K'
WHERE name = 'King'
   OR image_url IN ('/avatars/king.svg', 'king.svg');
